### ISSUE TITLE
yapp_fits2fil support for 4 pol data

### ISSUE THREAD

**Issue by devanshkv** [jayanthc/yapp#2]
Here is an example:

    yapp_fits2fil /hyrule/data/grbfrb/P3231/puppi_58163_B0950+08_0378_0001.fits
    WARNING: Number of IFs is 0! Setting it to 1.
    ERROR: Unsupported number of polarizations!

**Comment by jayanthc** [comment]
Thanks, @devanshkv. I'm in the process of supporting full-Stokes for `yapp_fits2fil`, but it could take a week or two.

**Comment by jayanthc** [comment]
@devanshkv: Not sure when I can get around to doing this. If you are so inclined, feel free to add the functionality, and send me a pull request. Thanks!

**Comment by devanshkv** [comment]
@jayanthc no worries, we were converting all `psrfits` to filterbank to run [`heimdall`](https://sourceforge.net/projects/heimdall-astro/). I wrote a code to dump `psrfits` to [`dada`](http://psrdada.sourceforge.net) buffers and run `heimdall` through the ring buffer.
In principle one can run `digifil` to convert from `dada` to `filterbank` if need.
